apiVersion: v1
kind: Service
metadata:
  name: argocd-learnning01
  namespace: argocd-learnning01
  labels:
spec:
  type: NodePort
  selector:
    app: argocd-learnning01
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
